### ISSUE TITLE
Portable Installation

### ISSUE THREAD

**Issue by Gavin-Holt** [felipedaragon/sandcat#5]
Hi,

I have tried installing to my USB stick at home - which maintains a constant drive letter (subst p: %CD%).

But this method does not allow me to run Sandcat on machines at work. There is a module not found error.

Is there another way of installing Sandcat for portable use?   
At work I do not have write access to the registry, nor can I add to the path!

Kind Regards Gavin Holt

**Comment by felipedaragon** [comment]
Hello Gavin! Did you try this https://github.com/felipedaragon/sandcat/blob/master/src/core/uMain.pas#L102? Create this empty JSON file within the Config subfolder and Sandcat should start in portable mode. However, this might not work in your situation because your environment and Registry restrictions may prevent Sciter from being registered.

**Comment by Gavin-Holt** [comment]
Hi

Many thanks for taking the time - your solution worked. I created an empty json file off the installation directory i.e. 'Config\Portable.json' and all works well.

Now I can start experimenting with Sandcat browser.

Kind Regards Gavin Holt
